language: java

jdk: openjdk11

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install

notifications:
  email:
    recipients:
  - mazelan95@gmail.com
    on_success: always
    on_failure: always
